spring:
  application:
    name: student
  datasource:
    # url: jdbc:mysql://localhost:3306/thinkitive
    # username: root
    # password: Root@1234
    # driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:postgresql://localhost:5433/thinkitive
    username: postgres
    password: root   
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8083
